services:
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: management_db
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"

  backend:
    build: ./management-backend
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/management_db
      SPRING_DATASOURCE_USERNAME: user
      SPRING_DATASOURCE_PASSWORD: password
    depends_on:
      - db

frontend:
  build: ./management-frontend
  ports:
    - "3000:3000"
  environment:
    NEXT_PUBLIC_API_URL: http://localhost:8080/api
    INTERNAL_API_URL: http://backend:8080/api
    AUTH_SECRET: ${AUTH_SECRET}
    AUTH_GITHUB_ID: ${AUTH_GITHUB_ID}
    AUTH_GITHUB_SECRET: ${AUTH_GITHUB_SECRET}
    AUTH_GOOGLE_ID: ${AUTH_GOOGLE_ID}
    AUTH_GOOGLE_SECRET: ${AUTH_GOOGLE_SECRET}
    # ACESTEA SUNT CRITICE:
    AUTH_URL: http://localhost:3000
    AUTH_TRUST_HOST: "true"
  depends_on:
    - backend
